using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "dbbd63b1de3b99bd")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IIntroductionContent, ISection2Content, ISection3Content
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Welcome Summary: Enter Welcome Summary
		///</summary>
		[ImplementPropertyType("welcomeSummary")]
		public IHtmlString WelcomeSummary
		{
			get { return this.GetPropertyValue<IHtmlString>("welcomeSummary"); }
		}

		///<summary>
		/// Welcome Title: Enter welcome title
		///</summary>
		[ImplementPropertyType("welcomeTitle")]
		public string WelcomeTitle
		{
			get { return this.GetPropertyValue<string>("welcomeTitle"); }
		}

		///<summary>
		/// Introduction: Enter your introduction text.
		///</summary>
		[ImplementPropertyType("introduction")]
		public IHtmlString Introduction
		{
			get { return Umbraco.Web.PublishedContentModels.IntroductionContent.GetIntroduction(this); }
		}

		///<summary>
		/// Section 2 Feature 1 Heading: Section 2 Feature 1 Heading
		///</summary>
		[ImplementPropertyType("section2Feature1Heading")]
		public string Section2Feature1Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature1Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 1 Summary: Section 2 Feature 1 Summary
		///</summary>
		[ImplementPropertyType("section2Feature1Summary")]
		public string Section2Feature1Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature1Summary(this); }
		}

		///<summary>
		/// Section 2 Feature 2 Heading: Enter Section 2 Feature 2 Heading
		///</summary>
		[ImplementPropertyType("section2Feature2Heading")]
		public string Section2Feature2Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature2Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 2 Summary: Enter Section 2 Feature 2 Summary
		///</summary>
		[ImplementPropertyType("section2Feature2Summary")]
		public string Section2Feature2Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature2Summary(this); }
		}

		///<summary>
		/// Section 2 Feature 3 Heading: Enter Section 2 Feature 3 Heading
		///</summary>
		[ImplementPropertyType("section2Feature3Heading")]
		public string Section2Feature3Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature3Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 3 Summary: Enter Section 2 Feature 3 Summary
		///</summary>
		[ImplementPropertyType("section2Feature3Summary")]
		public string Section2Feature3Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature3Summary(this); }
		}

		///<summary>
		/// Section 2 Feature 4 Heading: Enter Section 2 Feature 4 Heading
		///</summary>
		[ImplementPropertyType("section2Feature4Heading")]
		public string Section2Feature4Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature4Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 4 Summary: Enter Section 2 Feature 4 Summary
		///</summary>
		[ImplementPropertyType("section2Feature4Summary")]
		public string Section2Feature4Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature4Summary(this); }
		}

		///<summary>
		/// Section 2 Heading: Enter Section 2 Heading
		///</summary>
		[ImplementPropertyType("section2Heading")]
		public string Section2Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Heading(this); }
		}

		///<summary>
		/// Section 2 Summary: Enter Section 2 Summary
		///</summary>
		[ImplementPropertyType("section2Summary")]
		public string Section2Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Summary(this); }
		}

		///<summary>
		/// Section 3 Feature 1 Heading: Section 3 Feature 1 Heading
		///</summary>
		[ImplementPropertyType("section3Feature1Heading")]
		public string Section3Feature1Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature1Heading(this); }
		}

		///<summary>
		/// Section 3 Feature 1 Summary: Section 3 Feature 1 Summary
		///</summary>
		[ImplementPropertyType("section3Feature1Summary")]
		public string Section3Feature1Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature1Summary(this); }
		}

		///<summary>
		/// Section 3 Feature 2 Heading: Section 3 Feature 2 Heading
		///</summary>
		[ImplementPropertyType("section3Feature2Heading")]
		public string Section3Feature2Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature2Heading(this); }
		}

		///<summary>
		/// Section 3 Feature 2 Summary: Section 3 Feature 2 Summary
		///</summary>
		[ImplementPropertyType("section3Feature2Summary")]
		public string Section3Feature2Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature2Summary(this); }
		}

		///<summary>
		/// Section 3 Feature 3 Heading: Section 3 Feature 3 Heading
		///</summary>
		[ImplementPropertyType("section3Feature3Heading")]
		public string Section3Feature3Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature3Heading(this); }
		}

		///<summary>
		/// Section 3 Feature 3 Summary: Section 3 Feature 3 Summary
		///</summary>
		[ImplementPropertyType("section3Feature3Summary")]
		public string Section3Feature3Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature3Summary(this); }
		}

		///<summary>
		/// Section 3 Heading: Enter Section 3 Heading
		///</summary>
		[ImplementPropertyType("section3Heading")]
		public string Section3Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Heading(this); }
		}
	}

	/// <summary>Services</summary>
	[PublishedContentModel("services")]
	public partial class Services : PublishedContentModel, ISection3Content
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "services";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Services(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Services, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Section 3 Feature 1 Heading: Section 3 Feature 1 Heading
		///</summary>
		[ImplementPropertyType("section3Feature1Heading")]
		public string Section3Feature1Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature1Heading(this); }
		}

		///<summary>
		/// Section 3 Feature 1 Summary: Section 3 Feature 1 Summary
		///</summary>
		[ImplementPropertyType("section3Feature1Summary")]
		public string Section3Feature1Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature1Summary(this); }
		}

		///<summary>
		/// Section 3 Feature 2 Heading: Section 3 Feature 2 Heading
		///</summary>
		[ImplementPropertyType("section3Feature2Heading")]
		public string Section3Feature2Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature2Heading(this); }
		}

		///<summary>
		/// Section 3 Feature 2 Summary: Section 3 Feature 2 Summary
		///</summary>
		[ImplementPropertyType("section3Feature2Summary")]
		public string Section3Feature2Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature2Summary(this); }
		}

		///<summary>
		/// Section 3 Feature 3 Heading: Section 3 Feature 3 Heading
		///</summary>
		[ImplementPropertyType("section3Feature3Heading")]
		public string Section3Feature3Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature3Heading(this); }
		}

		///<summary>
		/// Section 3 Feature 3 Summary: Section 3 Feature 3 Summary
		///</summary>
		[ImplementPropertyType("section3Feature3Summary")]
		public string Section3Feature3Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Feature3Summary(this); }
		}

		///<summary>
		/// Section 3 Heading: Enter Section 3 Heading
		///</summary>
		[ImplementPropertyType("section3Heading")]
		public string Section3Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section3Content.GetSection3Heading(this); }
		}
	}

	/// <summary>WhyChooseUs</summary>
	[PublishedContentModel("whyChooseUs")]
	public partial class WhyChooseUs : PublishedContentModel, ISection2Content
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "whyChooseUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public WhyChooseUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WhyChooseUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Section 2 Feature 1 Heading: Section 2 Feature 1 Heading
		///</summary>
		[ImplementPropertyType("section2Feature1Heading")]
		public string Section2Feature1Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature1Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 1 Summary: Section 2 Feature 1 Summary
		///</summary>
		[ImplementPropertyType("section2Feature1Summary")]
		public string Section2Feature1Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature1Summary(this); }
		}

		///<summary>
		/// Section 2 Feature 2 Heading: Enter Section 2 Feature 2 Heading
		///</summary>
		[ImplementPropertyType("section2Feature2Heading")]
		public string Section2Feature2Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature2Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 2 Summary: Enter Section 2 Feature 2 Summary
		///</summary>
		[ImplementPropertyType("section2Feature2Summary")]
		public string Section2Feature2Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature2Summary(this); }
		}

		///<summary>
		/// Section 2 Feature 3 Heading: Enter Section 2 Feature 3 Heading
		///</summary>
		[ImplementPropertyType("section2Feature3Heading")]
		public string Section2Feature3Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature3Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 3 Summary: Enter Section 2 Feature 3 Summary
		///</summary>
		[ImplementPropertyType("section2Feature3Summary")]
		public string Section2Feature3Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature3Summary(this); }
		}

		///<summary>
		/// Section 2 Feature 4 Heading: Enter Section 2 Feature 4 Heading
		///</summary>
		[ImplementPropertyType("section2Feature4Heading")]
		public string Section2Feature4Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature4Heading(this); }
		}

		///<summary>
		/// Section 2 Feature 4 Summary: Enter Section 2 Feature 4 Summary
		///</summary>
		[ImplementPropertyType("section2Feature4Summary")]
		public string Section2Feature4Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Feature4Summary(this); }
		}

		///<summary>
		/// Section 2 Heading: Enter Section 2 Heading
		///</summary>
		[ImplementPropertyType("section2Heading")]
		public string Section2Heading
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Heading(this); }
		}

		///<summary>
		/// Section 2 Summary: Enter Section 2 Summary
		///</summary>
		[ImplementPropertyType("section2Summary")]
		public string Section2Summary
		{
			get { return Umbraco.Web.PublishedContentModels.Section2Content.GetSection2Summary(this); }
		}
	}

	// Mixin content Type 1150 with alias "introductionContent"
	/// <summary>Introduction Content</summary>
	public partial interface IIntroductionContent : IPublishedContent
	{
		/// <summary>Introduction</summary>
		IHtmlString Introduction { get; }
	}

	/// <summary>Introduction Content</summary>
	[PublishedContentModel("introductionContent")]
	public partial class IntroductionContent : PublishedContentModel, IIntroductionContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "introductionContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public IntroductionContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<IntroductionContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Introduction: Enter your introduction text.
		///</summary>
		[ImplementPropertyType("introduction")]
		public IHtmlString Introduction
		{
			get { return GetIntroduction(this); }
		}

		/// <summary>Static getter for Introduction</summary>
		public static IHtmlString GetIntroduction(IIntroductionContent that) { return that.GetPropertyValue<IHtmlString>("introduction"); }
	}

	/// <summary>Details</summary>
	[PublishedContentModel("details")]
	public partial class Details : PublishedContentModel, IDetailsContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "details";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Details(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Details, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Details: Enter your details
		///</summary>
		[ImplementPropertyType("details")]
		public IHtmlString Details
		{
			get { return Umbraco.Web.PublishedContentModels.DetailsContent.GetDetails(this); }
		}
	}

	// Mixin content Type 1154 with alias "detailsContent"
	/// <summary>Details Content</summary>
	public partial interface IDetailsContent : IPublishedContent
	{
		/// <summary>Details</summary>
		IHtmlString Details { get; }
	}

	/// <summary>Details Content</summary>
	[PublishedContentModel("detailsContent")]
	public partial class DetailsContent : PublishedContentModel, IDetailsContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "detailsContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DetailsContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DetailsContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Details: Enter your details
		///</summary>
		[ImplementPropertyType("details")]
		public IHtmlString Details
		{
			get { return GetDetails(this); }
		}

		/// <summary>Static getter for Details</summary>
		public static IHtmlString GetDetails(IDetailsContent that) { return that.GetPropertyValue<IHtmlString>("details"); }
	}

	// Mixin content Type 1182 with alias "section2Content"
	/// <summary>Section 2 Content</summary>
	public partial interface ISection2Content : IPublishedContent
	{
		/// <summary>Section 2 Feature 1 Heading</summary>
		string Section2Feature1Heading { get; }

		/// <summary>Section 2 Feature 1 Summary</summary>
		string Section2Feature1Summary { get; }

		/// <summary>Section 2 Feature 2 Heading</summary>
		string Section2Feature2Heading { get; }

		/// <summary>Section 2 Feature 2 Summary</summary>
		string Section2Feature2Summary { get; }

		/// <summary>Section 2 Feature 3 Heading</summary>
		string Section2Feature3Heading { get; }

		/// <summary>Section 2 Feature 3 Summary</summary>
		string Section2Feature3Summary { get; }

		/// <summary>Section 2 Feature 4 Heading</summary>
		string Section2Feature4Heading { get; }

		/// <summary>Section 2 Feature 4 Summary</summary>
		string Section2Feature4Summary { get; }

		/// <summary>Section 2 Heading</summary>
		string Section2Heading { get; }

		/// <summary>Section 2 Summary</summary>
		string Section2Summary { get; }
	}

	/// <summary>Section 2 Content</summary>
	[PublishedContentModel("section2Content")]
	public partial class Section2Content : PublishedContentModel, ISection2Content
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "section2Content";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Section2Content(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Section2Content, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Section 2 Feature 1 Heading: Section 2 Feature 1 Heading
		///</summary>
		[ImplementPropertyType("section2Feature1Heading")]
		public string Section2Feature1Heading
		{
			get { return GetSection2Feature1Heading(this); }
		}

		/// <summary>Static getter for Section 2 Feature 1 Heading</summary>
		public static string GetSection2Feature1Heading(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature1Heading"); }

		///<summary>
		/// Section 2 Feature 1 Summary: Section 2 Feature 1 Summary
		///</summary>
		[ImplementPropertyType("section2Feature1Summary")]
		public string Section2Feature1Summary
		{
			get { return GetSection2Feature1Summary(this); }
		}

		/// <summary>Static getter for Section 2 Feature 1 Summary</summary>
		public static string GetSection2Feature1Summary(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature1Summary"); }

		///<summary>
		/// Section 2 Feature 2 Heading: Enter Section 2 Feature 2 Heading
		///</summary>
		[ImplementPropertyType("section2Feature2Heading")]
		public string Section2Feature2Heading
		{
			get { return GetSection2Feature2Heading(this); }
		}

		/// <summary>Static getter for Section 2 Feature 2 Heading</summary>
		public static string GetSection2Feature2Heading(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature2Heading"); }

		///<summary>
		/// Section 2 Feature 2 Summary: Enter Section 2 Feature 2 Summary
		///</summary>
		[ImplementPropertyType("section2Feature2Summary")]
		public string Section2Feature2Summary
		{
			get { return GetSection2Feature2Summary(this); }
		}

		/// <summary>Static getter for Section 2 Feature 2 Summary</summary>
		public static string GetSection2Feature2Summary(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature2Summary"); }

		///<summary>
		/// Section 2 Feature 3 Heading: Enter Section 2 Feature 3 Heading
		///</summary>
		[ImplementPropertyType("section2Feature3Heading")]
		public string Section2Feature3Heading
		{
			get { return GetSection2Feature3Heading(this); }
		}

		/// <summary>Static getter for Section 2 Feature 3 Heading</summary>
		public static string GetSection2Feature3Heading(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature3Heading"); }

		///<summary>
		/// Section 2 Feature 3 Summary: Enter Section 2 Feature 3 Summary
		///</summary>
		[ImplementPropertyType("section2Feature3Summary")]
		public string Section2Feature3Summary
		{
			get { return GetSection2Feature3Summary(this); }
		}

		/// <summary>Static getter for Section 2 Feature 3 Summary</summary>
		public static string GetSection2Feature3Summary(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature3Summary"); }

		///<summary>
		/// Section 2 Feature 4 Heading: Enter Section 2 Feature 4 Heading
		///</summary>
		[ImplementPropertyType("section2Feature4Heading")]
		public string Section2Feature4Heading
		{
			get { return GetSection2Feature4Heading(this); }
		}

		/// <summary>Static getter for Section 2 Feature 4 Heading</summary>
		public static string GetSection2Feature4Heading(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature4Heading"); }

		///<summary>
		/// Section 2 Feature 4 Summary: Enter Section 2 Feature 4 Summary
		///</summary>
		[ImplementPropertyType("section2Feature4Summary")]
		public string Section2Feature4Summary
		{
			get { return GetSection2Feature4Summary(this); }
		}

		/// <summary>Static getter for Section 2 Feature 4 Summary</summary>
		public static string GetSection2Feature4Summary(ISection2Content that) { return that.GetPropertyValue<string>("section2Feature4Summary"); }

		///<summary>
		/// Section 2 Heading: Enter Section 2 Heading
		///</summary>
		[ImplementPropertyType("section2Heading")]
		public string Section2Heading
		{
			get { return GetSection2Heading(this); }
		}

		/// <summary>Static getter for Section 2 Heading</summary>
		public static string GetSection2Heading(ISection2Content that) { return that.GetPropertyValue<string>("section2Heading"); }

		///<summary>
		/// Section 2 Summary: Enter Section 2 Summary
		///</summary>
		[ImplementPropertyType("section2Summary")]
		public string Section2Summary
		{
			get { return GetSection2Summary(this); }
		}

		/// <summary>Static getter for Section 2 Summary</summary>
		public static string GetSection2Summary(ISection2Content that) { return that.GetPropertyValue<string>("section2Summary"); }
	}

	// Mixin content Type 1190 with alias "section3Content"
	/// <summary>Section 3 Content</summary>
	public partial interface ISection3Content : IPublishedContent
	{
		/// <summary>Section 3 Feature 1 Heading</summary>
		string Section3Feature1Heading { get; }

		/// <summary>Section 3 Feature 1 Summary</summary>
		string Section3Feature1Summary { get; }

		/// <summary>Section 3 Feature 2 Heading</summary>
		string Section3Feature2Heading { get; }

		/// <summary>Section 3 Feature 2 Summary</summary>
		string Section3Feature2Summary { get; }

		/// <summary>Section 3 Feature 3 Heading</summary>
		string Section3Feature3Heading { get; }

		/// <summary>Section 3 Feature 3 Summary</summary>
		string Section3Feature3Summary { get; }

		/// <summary>Section 3 Heading</summary>
		string Section3Heading { get; }
	}

	/// <summary>Section 3 Content</summary>
	[PublishedContentModel("section3Content")]
	public partial class Section3Content : PublishedContentModel, ISection3Content
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "section3Content";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Section3Content(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Section3Content, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Section 3 Feature 1 Heading: Section 3 Feature 1 Heading
		///</summary>
		[ImplementPropertyType("section3Feature1Heading")]
		public string Section3Feature1Heading
		{
			get { return GetSection3Feature1Heading(this); }
		}

		/// <summary>Static getter for Section 3 Feature 1 Heading</summary>
		public static string GetSection3Feature1Heading(ISection3Content that) { return that.GetPropertyValue<string>("section3Feature1Heading"); }

		///<summary>
		/// Section 3 Feature 1 Summary: Section 3 Feature 1 Summary
		///</summary>
		[ImplementPropertyType("section3Feature1Summary")]
		public string Section3Feature1Summary
		{
			get { return GetSection3Feature1Summary(this); }
		}

		/// <summary>Static getter for Section 3 Feature 1 Summary</summary>
		public static string GetSection3Feature1Summary(ISection3Content that) { return that.GetPropertyValue<string>("section3Feature1Summary"); }

		///<summary>
		/// Section 3 Feature 2 Heading: Section 3 Feature 2 Heading
		///</summary>
		[ImplementPropertyType("section3Feature2Heading")]
		public string Section3Feature2Heading
		{
			get { return GetSection3Feature2Heading(this); }
		}

		/// <summary>Static getter for Section 3 Feature 2 Heading</summary>
		public static string GetSection3Feature2Heading(ISection3Content that) { return that.GetPropertyValue<string>("section3Feature2Heading"); }

		///<summary>
		/// Section 3 Feature 2 Summary: Section 3 Feature 2 Summary
		///</summary>
		[ImplementPropertyType("section3Feature2Summary")]
		public string Section3Feature2Summary
		{
			get { return GetSection3Feature2Summary(this); }
		}

		/// <summary>Static getter for Section 3 Feature 2 Summary</summary>
		public static string GetSection3Feature2Summary(ISection3Content that) { return that.GetPropertyValue<string>("section3Feature2Summary"); }

		///<summary>
		/// Section 3 Feature 3 Heading: Section 3 Feature 3 Heading
		///</summary>
		[ImplementPropertyType("section3Feature3Heading")]
		public string Section3Feature3Heading
		{
			get { return GetSection3Feature3Heading(this); }
		}

		/// <summary>Static getter for Section 3 Feature 3 Heading</summary>
		public static string GetSection3Feature3Heading(ISection3Content that) { return that.GetPropertyValue<string>("section3Feature3Heading"); }

		///<summary>
		/// Section 3 Feature 3 Summary: Section 3 Feature 3 Summary
		///</summary>
		[ImplementPropertyType("section3Feature3Summary")]
		public string Section3Feature3Summary
		{
			get { return GetSection3Feature3Summary(this); }
		}

		/// <summary>Static getter for Section 3 Feature 3 Summary</summary>
		public static string GetSection3Feature3Summary(ISection3Content that) { return that.GetPropertyValue<string>("section3Feature3Summary"); }

		///<summary>
		/// Section 3 Heading: Enter Section 3 Heading
		///</summary>
		[ImplementPropertyType("section3Heading")]
		public string Section3Heading
		{
			get { return GetSection3Heading(this); }
		}

		/// <summary>Static getter for Section 3 Heading</summary>
		public static string GetSection3Heading(ISection3Content that) { return that.GetPropertyValue<string>("section3Heading"); }
	}

	/// <summary>ContactUs</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
